### ISSUE TITLE
How can i study input-output correlation?

### ISSUE THREAD

**Issue by francescopatane96** [Johnsunnn/ExamPle#1]
hi! great work! i'm trying adapting your model in a study case of my interest and i'd like to study the correlation between input (aminoacids) and output (positive,negative) like in your published paper. how can i do this task? thank you 
Francesco, University of Padova

**Comment by FakeEnd** [comment]
Sorry for replying late. Thank you for your attention to our paper. However, due to recent busy graduation matters, I will need about a week to tidy up the experimental code. May be I can upload the code in one week later.:)

**Comment by francescopatane96** [comment]
Thank you very much... i appreciate it :)
Francesco

**Comment by FakeEnd** [comment]
> Thank you very much... i appreciate it :) Francesco

I have pushed the experiment code in this github respository. If you have any questions, welcome to ask.

**Comment by francescopatane96** [comment]
> > Thank you very much... i appreciate it :) Francesco
> 
> I have pushed the experiment code in this github respository. If you have any questions, welcome to ask.

thank you :)
