### ISSUE TITLE
Request instructions for use

### ISSUE THREAD

**Issue by zxgsy520** [Johnsunnn/ExamPle#3]
Hello! 
     May I ask if you can provide instructions for using this software? Is the input a genetically predicted protein?
Could you please reply, thank you!

**Comment by Johnsunnn** [comment]
Hello! Thanks for your attention. We haven't developed it as a software application, so you can run the python code to use it. The file main.py is the code used for training and testing procedure. The input is the protein sequence and you can see the samples in the dataset file. If you want to use it directly without training, I can upload the trained model. Let me know if you need it.

**Comment by Johnsunnn** [comment]
> Hello! May I ask if you can provide instructions for using this software? Is the input a genetically predicted protein? Could you please reply, thank you!

Hello! Thanks for your attention. We haven't developed it as a software application, so you can run the python code to use it. The file main.py is the code used for training and testing procedure. The input is the protein sequence and you can see the samples in the dataset file. If you want to use it directly without training procedure, I can upload the trained model. Let me know if you need it.

**Comment by zxgsy520** [comment]
Hello, I don't have a training data. Could you please upload the trained model. Thank you!

**Comment by Johnsunnn** [comment]
> Hello, I don't have a training data. Could you please upload the trained model. Thank you!

Since the trained model file is too large to upload, could you give me your email address? So that I can send you the trained model file directly.

**Comment by zxgsy520** [comment]
My email: invicoun@foxmail.com
Thank you!

**Comment by namhsuya** [comment]
> > Hello, I don't have a training data. Could you please upload the trained model. Thank you!
> 
> Since the trained model file is too large to upload, could you give me your email address? So that I can send you the trained model file directly.

Hi, could you kindly share the model?
email: ayushmaan.banerjee@gmail.com

Thanks!

**Comment by Johnsunnn** [comment]
> Hi, could you kindly share the model? email: [ayushmaan.banerjee@gmail.com](mailto:ayushmaan.banerjee@gmail.com)
> 
> Thanks!

The model has been sent to your email address. Thanks for your attention.
